version: "3.8"

services:
  app:
    build: .
    container_name: bclis-api
    restart: always
    env_file: ./.env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: mysql:9.0.1-oracle
    restart: always
    container_name: mysqldb
    env_file: ./.env
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql


volumes:
  mysql:
    external: true